version: '3.8'

services:
  postgres_db:
    image: postgres:16-alpine
    env_file: ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  goose_migrations:
    build: .
    env_file: ".env"
    depends_on:
      postgres_db:
        condition: service_healthy
    entrypoint: ["./migrations"]

  timezonebot:
    build: .
    env_file: ".env"
    depends_on:
      goose_migrations:
        condition: service_completed_successfully

volumes:
  postgres_data: {}