// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

type Stream struct {
	GuildID      string
	AlertChannel string
}

type Timezone struct {
	UserID   string
	Timezone string
}
