// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stream.sql

package database

import (
	"context"
)

const getAlertChannel = `-- name: GetAlertChannel :one
SELECT alert_channel FROM streams WHERE guild_id = $1
`

func (q *Queries) GetAlertChannel(ctx context.Context, guildID string) (string, error) {
	row := q.db.QueryRow(ctx, getAlertChannel, guildID)
	var alert_channel string
	err := row.Scan(&alert_channel)
	return alert_channel, err
}

const isStreamAlertEnabled = `-- name: IsStreamAlertEnabled :one
SELECT EXISTS (SELECT 1 FROM streams WHERE guild_id = $1) AS enabled
`

func (q *Queries) IsStreamAlertEnabled(ctx context.Context, guildID string) (bool, error) {
	row := q.db.QueryRow(ctx, isStreamAlertEnabled, guildID)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}

const setAlertChannel = `-- name: SetAlertChannel :exec
INSERT INTO streams (guild_id, alert_channel) VALUES ($1, $2) ON CONFLICT (guild_id) DO UPDATE SET alert_channel = $2
`

type SetAlertChannelParams struct {
	GuildID      string
	AlertChannel string
}

func (q *Queries) SetAlertChannel(ctx context.Context, arg SetAlertChannelParams) error {
	_, err := q.db.Exec(ctx, setAlertChannel, arg.GuildID, arg.AlertChannel)
	return err
}
