// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: timezones.sql

package database

import (
	"context"
)

const getTimezone = `-- name: GetTimezone :one
SELECT timezone FROM timezones WHERE user_id = $1
`

func (q *Queries) GetTimezone(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRow(ctx, getTimezone, userID)
	var timezone string
	err := row.Scan(&timezone)
	return timezone, err
}

const setTimezone = `-- name: SetTimezone :exec
INSERT INTO timezones (user_id, timezone) VALUES ($1, $2) ON CONFLICT (user_id) DO UPDATE SET timezone = $2
`

type SetTimezoneParams struct {
	UserID   string
	Timezone string
}

func (q *Queries) SetTimezone(ctx context.Context, arg SetTimezoneParams) error {
	_, err := q.db.Exec(ctx, setTimezone, arg.UserID, arg.Timezone)
	return err
}
